server:
  port: 9002
spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8889/eureka/
zuul:
  routes:
    api:
      path: /api/**
      serviceId: client
